export default function CustomerAISummary() {
    // ---- STATIC, SAFE MOCK DATA ----
    const summaries = [
      {
        id: 1,
        customer: "Alice Johnson",
        summary:
          "Alice is a highly engaged customer with frequent recent interactions. She has shown interest in premium offerings and responds quickly to outreach. Recommended action is to introduce upsell options while maintaining proactive support.",
      },
      {
        id: 2,
        customer: "Bob Smith",
        summary:
          "Bob has limited recent engagement and has not been contacted in over two weeks. He recently reported an issue, indicating potential dissatisfaction. Immediate follow-up is recommended to reduce churn risk.",
      },
      {
        id: 3,
        customer: "Charlie Davis",
        summary:
          "Charlie maintains steady engagement and has expressed interest in pricing details. Continued nurturing and timely responses may convert interest into long-term value.",
      },
    ];
  
    return (
      <div className="space-y-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm transition-all
duration-200
ease-out hover:-translate-y-0.5 hover:shadow-l
">
        <div>
          <h3 className="font-semibold text-slate-900 dark:text-white">
            AI Customer Summaries
          </h3>
          <p className="text-sm text-slate-500">
            AI-generated overview based on unified CRM activity
          </p>
        </div>
  
        {summaries.map((item) => (
          <div
            key={item.id}
            className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm space-y-2"
          >
            <p className="font-medium text-slate-900 dark:text-white">
              {item.customer}
            </p>
  
            <p className="text-sm text-slate-600 leading-relaxed">
              {item.summary}
            </p>
  
            <p className="text-xs text-slate-400">
              Generated by AI • CRM Insights
            </p>
          </div>
        ))}
      </div>
    );
  }
  